import { Badge } from "@/components/common/Badge";
import { TextInput } from "@/components/forms/Input";
import { Select } from "@/components/forms/Select";
import { SEASON_OPTIONS, type Season } from "@/lib/master-data/seasons";
import type { MillOfferStatus } from "@/lib/types/millOffer";
import { MILL_OFFER_STATUS_OPTIONS } from "@/lib/types/millOffer";

interface OfferInformationSectionProps {
  offerNumber?: string;
  status: MillOfferStatus;
  offerDate: string;
  validTill: string;
  season: Season;
  onChange: (patch: { offerDate?: string; validTill?: string; season?: Season }) => void;
  errors?: Partial<Record<"offerDate" | "validTill", string>>;
  readOnly?: boolean;
}

/**
 * Offer Information section. Offer Number is auto-generated by the
 * service on save (Business Rule: "Offer Number must be unique") and
 * shown read-only here. Status is displayed, not directly editable —
 * transitions happen via the Publish/Withdraw/Duplicate actions so the
 * "Published offers become read-only" rule can't be bypassed by editing
 * the status field directly.
 */
export function OfferInformationSection({
  offerNumber,
  status,
  offerDate,
  validTill,
  season,
  onChange,
  errors = {},
  readOnly = false,
}: OfferInformationSectionProps) {
  const statusLabel = MILL_OFFER_STATUS_OPTIONS.find((s) => s.value === status)?.label ?? status;

  return (
    <div>
      <h2 className="font-display text-lg font-medium text-charcoal dark:text-white">Offer Information</h2>
      <div className="mt-5 grid sm:grid-cols-2 gap-5">
        <div>
          <p className="text-[13px] font-medium text-charcoal dark:text-white mb-1.5">Offer Number</p>
          <p className="h-11 flex items-center px-3.5 rounded-sm border border-line dark:border-white/10 bg-charcoal/[0.02] font-mono text-sm text-ink-soft dark:text-white/50">
            {offerNumber ?? "Assigned automatically on save"}
          </p>
        </div>
        <div>
          <p className="text-[13px] font-medium text-charcoal dark:text-white mb-1.5">Offer Status</p>
          <div className="h-11 flex items-center px-3.5 rounded-sm border border-line dark:border-white/10 bg-charcoal/[0.02]">
            <Badge tone={status === "published" ? "verified" : status === "cancelled" || status === "expired" ? "urgent" : "charcoal"}>
              {statusLabel}
            </Badge>
          </div>
        </div>
        <TextInput
          label="Offer Date"
          type="date"
          value={offerDate}
          onChange={(e) => onChange({ offerDate: e.target.value })}
          error={errors.offerDate}
          disabled={readOnly}
        />
        <TextInput
          label="Offer Valid Till"
          type="date"
          value={validTill}
          onChange={(e) => onChange({ validTill: e.target.value })}
          error={errors.validTill}
          disabled={readOnly}
        />
        <Select
          label="Season"
          defaultValue={season}
          options={SEASON_OPTIONS}
          onChange={(e) => onChange({ season: e.target.value as Season })}
          disabled={readOnly}
        />
      </div>
    </div>
  );
}
