import { MILLS } from "@/lib/master-data/mills";
import { STATES } from "@/lib/master-data/states";
import { marketIntelligenceService } from "./marketIntelligence.service";
import { millTenderService } from "./millTender.service";
import { getMasterStateLabel } from "@/lib/utils/marketplaceLabels";
import type { WatchlistItem, WatchlistNotification, WatchTargetType } from "@/lib/types/smartMatch";

const WATCHLIST_KEY = "tradesucro-watchlist-items";
const NOTIFICATIONS_KEY = "tradesucro-watchlist-notifications";
const NETWORK_DELAY_MS = 300;

function delay<T>(value: T, ms = NETWORK_DELAY_MS): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

function readJSON<T>(key: string, fallback: () => T): T {
  if (typeof window === "undefined") return fallback();
  try {
    const raw = window.localStorage.getItem(key);
    if (raw) return JSON.parse(raw) as T;
  } catch {
    // fall through
  }
  const seeded = fallback();
  window.localStorage.setItem(key, JSON.stringify(seeded));
  return seeded;
}

function writeJSON<T>(key: string, value: T) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(key, JSON.stringify(value));
}

function seedWatchlist(): WatchlistItem[] {
  return [
    { id: "watch-1", targetType: "mill", targetValue: MILLS[0].id, targetLabel: MILLS[0].name, createdAt: new Date(Date.now() - 5 * 86400000).toISOString() },
    { id: "watch-2", targetType: "grade", targetValue: "S30", targetLabel: "S30", createdAt: new Date(Date.now() - 3 * 86400000).toISOString() },
    { id: "watch-3", targetType: "state", targetValue: STATES[0].value, targetLabel: STATES[0].label, createdAt: new Date(Date.now() - 1 * 86400000).toISOString() },
  ];
}

function readItems(): WatchlistItem[] {
  return readJSON(WATCHLIST_KEY, seedWatchlist);
}

function readNotifications(): WatchlistNotification[] {
  return readJSON(NOTIFICATIONS_KEY, () => []);
}

function nextId(prefix: string): string {
  return `${prefix}-${Date.now()}`;
}

/**
 * Watchlist Service (mock)
 * ------------------------------------------------------------------
 * No backend. Follow/unfollow state is local; "change" notifications
 * are generated by comparing a watched item's target against existing
 * (unmodified) market data — e.g. a watched mill's latest price move,
 * or a watched state's newly awarded tender — rather than a parallel
 * event system.
 */
export const watchlistService = {
  async getWatchlist(): Promise<WatchlistItem[]> {
    return delay([...readItems()].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));
  },

  async isWatched(targetType: WatchTargetType, targetValue: string): Promise<boolean> {
    return readItems().some((w) => w.targetType === targetType && w.targetValue === targetValue);
  },

  async addToWatchlist(targetType: WatchTargetType, targetValue: string, targetLabel: string): Promise<WatchlistItem> {
    const items = readItems();
    const existing = items.find((w) => w.targetType === targetType && w.targetValue === targetValue);
    if (existing) return delay(existing, 150);

    const item: WatchlistItem = { id: nextId("watch"), targetType, targetValue, targetLabel, createdAt: new Date().toISOString() };
    writeJSON(WATCHLIST_KEY, [item, ...items]);
    return delay(item, 300);
  },

  async removeFromWatchlist(id: string): Promise<void> {
    writeJSON(WATCHLIST_KEY, readItems().filter((w) => w.id !== id));
    return delay(undefined, 250);
  },

  async getNotifications(): Promise<WatchlistNotification[]> {
    const items = readItems();
    if (items.length === 0) return delay([]);

    const [livePrices, tenders] = await Promise.all([marketIntelligenceService.getLivePrices(), millTenderService.getTenders()]);
    const generated: WatchlistNotification[] = [];

    items.forEach((item) => {
      if (item.targetType === "mill") {
        const entry = livePrices.find((p) => p.millId === item.targetValue);
        if (entry && entry.todaysPrice !== entry.previousPrice) {
          const diff = entry.todaysPrice - entry.previousPrice;
          generated.push({
            id: `wn-mill-${item.id}`,
            watchlistItemId: item.id,
            targetLabel: item.targetLabel,
            title: `${item.targetLabel} price ${diff > 0 ? "increased" : "decreased"}`,
            description: `Now ₹${entry.todaysPrice.toLocaleString("en-IN")}/QTL (${diff > 0 ? "+" : ""}₹${diff.toLocaleString("en-IN")}).`,
            timestamp: entry.timeUpdated,
            read: false,
          });
        }
      } else if (item.targetType === "grade") {
        const matches = livePrices.filter((p) => p.grade === item.targetValue && p.offerAvailable);
        if (matches.length > 0) {
          generated.push({
            id: `wn-grade-${item.id}`,
            watchlistItemId: item.id,
            targetLabel: item.targetLabel,
            title: `${matches.length} active offers in ${item.targetLabel}`,
            description: `${matches[0].millName} and ${Math.max(0, matches.length - 1)} other mill(s) currently offering ${item.targetLabel}.`,
            timestamp: matches[0].timeUpdated,
            read: false,
          });
        }
      } else if (item.targetType === "state" || item.targetType === "region") {
        const stateLabel = getMasterStateLabel(item.targetValue) || item.targetLabel;
        const openTenders = tenders.filter((t) => t.status === "published");
        if (openTenders.length > 0) {
          generated.push({
            id: `wn-state-${item.id}`,
            watchlistItemId: item.id,
            targetLabel: item.targetLabel,
            title: `New tender activity near ${stateLabel}`,
            description: `${openTenders[0].tenderNumber} is open for bidding.`,
            timestamp: openTenders[0].updatedAt,
            read: false,
          });
        }
      } else if (item.targetType === "trader") {
        generated.push({
          id: `wn-trader-${item.id}`,
          watchlistItemId: item.id,
          targetLabel: item.targetLabel,
          title: `${item.targetLabel} listed new inventory`,
          description: `A new resale offer was published by this trader.`,
          timestamp: new Date(Date.now() - 3600000).toISOString(),
          read: true,
        });
      }
    });

    const stored = readNotifications();
    const merged = [...generated, ...stored.filter((s) => !generated.some((g) => g.id === s.id))];
    return delay(merged.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()));
  },

  async markAsRead(id: string): Promise<void> {
    const notifications = readNotifications();
    const existing = notifications.find((n) => n.id === id);
    const updated = existing
      ? notifications.map((n) => (n.id === id ? { ...n, read: true } : n))
      : [...notifications, { id, watchlistItemId: "", targetLabel: "", title: "", description: "", timestamp: new Date().toISOString(), read: true }];
    writeJSON(NOTIFICATIONS_KEY, updated);
  },
};
